server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true